name: "Unit Tests"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - run: yarn run test
    - uses: ./
      with: 
        milliseconds: 1000
